/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import crud.crud;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class FrameApp extends javax.swing.JFrame {
    crud mycode;

    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        this.setLocationRelativeTo(null);
        mycode= new crud();
        mycode.tampilDataMempelaiLaki(tabelMempelaiLaki, "SELECT*FROM mempelai_laki_laki");
        mycode.tampilDataPendaftaran(tabelPendaftaran, "SELECT*FROM pendaftaran");
        mycode.tampilDataValidasi(tabelValidasi, "SELECT*FROM validasi");
        mycode.tampilDataMempelaiPerempuan(tabelMempelaiPerempuan, "SELECT*FROM mempelai_perempuan");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlPendaftaran = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtKodeKelurahan = new javax.swing.JTextField();
        txtIdAdminPen = new javax.swing.JTextField();
        txtTglPernikahan = new javax.swing.JTextField();
        btnHpsPen = new javax.swing.JButton();
        btnSmpnPen = new javax.swing.JButton();
        btnUbhPen = new javax.swing.JButton();
        txtCariPendaftaran = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelPendaftaran = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        txtNoPendaftaran = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtStatusPen = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtTglPendaftaran = new javax.swing.JTextField();
        pnlML = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtNoPendaftaranML = new javax.swing.JTextField();
        txtIdUserML = new javax.swing.JTextField();
        txtNamaML = new javax.swing.JTextField();
        btnHpsML = new javax.swing.JButton();
        btnSmpnML = new javax.swing.JButton();
        btnUbhML = new javax.swing.JButton();
        txtCariMempelaiLaki = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelMempelaiLaki = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        txtIdMempelaiLaki = new javax.swing.JTextField();
        txtTempatLahirML = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtAgamaML = new javax.swing.JTextField();
        txtKwnML = new javax.swing.JTextField();
        txtPekerjaanML = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtUsiaML = new javax.swing.JTextField();
        txtAlamatML = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txtPendidikanML = new javax.swing.JTextField();
        txtStatusML = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txtTanggalLahirML = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        pnlMP = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        txtNoPendaftaranMP = new javax.swing.JTextField();
        txtIdUserMP = new javax.swing.JTextField();
        txtNamaMP = new javax.swing.JTextField();
        btnHpsMP = new javax.swing.JButton();
        btnSmpnMP = new javax.swing.JButton();
        btnUbhMP = new javax.swing.JButton();
        txtCariMempelaiPerempuan = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabelMempelaiPerempuan = new javax.swing.JTable();
        jLabel51 = new javax.swing.JLabel();
        txtIdMempelaiPerempuan = new javax.swing.JTextField();
        txtTempatLahirMP = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        txtAgamaMP = new javax.swing.JTextField();
        txtKwnMP = new javax.swing.JTextField();
        txtPekerjaanMP = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        txtUsiaMP = new javax.swing.JTextField();
        txtAlamatMP = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        txtPendidikanMP = new javax.swing.JTextField();
        txtStatusMP = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        txtTanggalLahirMP = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        pnlValidasi = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtNoPendaftaranVal = new javax.swing.JTextField();
        txtIdAdminVal = new javax.swing.JTextField();
        txtTglValidasi = new javax.swing.JTextField();
        btnHpsVal = new javax.swing.JButton();
        btnSmpnVal = new javax.swing.JButton();
        btnUbhVal = new javax.swing.JButton();
        txtCariValidasi = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelValidasi = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        txtNoValidasi = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtHasil = new javax.swing.JTextField();
        txtCatatanTambahan = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnPendaftaran = new javax.swing.JButton();
        btnML = new javax.swing.JButton();
        btnMP = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnValidasi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setBackground(new java.awt.Color(153, 204, 255));
        Content.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        Content.add(pnlHome, "card6");

        pnlPendaftaran.setBackground(new java.awt.Color(204, 204, 204));
        pnlPendaftaran.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Tanggal Pernikahan");
        pnlPendaftaran.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 170, -1));

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Kode Kelurahan");
        pnlPendaftaran.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 130, -1));

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("ID Admin");
        pnlPendaftaran.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtKodeKelurahan.setBackground(new java.awt.Color(255, 255, 255));
        txtKodeKelurahan.setForeground(new java.awt.Color(0, 0, 0));
        pnlPendaftaran.add(txtKodeKelurahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 220, -1));

        txtIdAdminPen.setBackground(new java.awt.Color(255, 255, 255));
        txtIdAdminPen.setForeground(new java.awt.Color(0, 0, 0));
        txtIdAdminPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdAdminPenActionPerformed(evt);
            }
        });
        pnlPendaftaran.add(txtIdAdminPen, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 220, -1));

        txtTglPernikahan.setBackground(new java.awt.Color(255, 255, 255));
        txtTglPernikahan.setForeground(new java.awt.Color(0, 0, 0));
        pnlPendaftaran.add(txtTglPernikahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 220, -1));

        btnHpsPen.setText("HAPUS");
        btnHpsPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsPenActionPerformed(evt);
            }
        });
        pnlPendaftaran.add(btnHpsPen, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 80, -1));

        btnSmpnPen.setText("SIMPAN");
        btnSmpnPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnPenActionPerformed(evt);
            }
        });
        pnlPendaftaran.add(btnSmpnPen, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        btnUbhPen.setText("UBAH");
        btnUbhPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhPenActionPerformed(evt);
            }
        });
        pnlPendaftaran.add(btnUbhPen, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 80, -1));

        txtCariPendaftaran.setBackground(new java.awt.Color(255, 255, 255));
        txtCariPendaftaran.setForeground(new java.awt.Color(0, 0, 0));
        txtCariPendaftaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariPendaftaranKeyReleased(evt);
            }
        });
        pnlPendaftaran.add(txtCariPendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 410, -1));

        tabelPendaftaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabelPendaftaran);

        pnlPendaftaran.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 500, 155));

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("No Pendaftaran");
        pnlPendaftaran.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtNoPendaftaran.setBackground(new java.awt.Color(255, 255, 255));
        txtNoPendaftaran.setForeground(new java.awt.Color(0, 0, 0));
        txtNoPendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoPendaftaranActionPerformed(evt);
            }
        });
        pnlPendaftaran.add(txtNoPendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 220, -1));

        jLabel22.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Status");
        pnlPendaftaran.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 132, -1));

        txtStatusPen.setBackground(new java.awt.Color(255, 255, 255));
        txtStatusPen.setForeground(new java.awt.Color(0, 0, 0));
        pnlPendaftaran.add(txtStatusPen, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 220, -1));

        jLabel30.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Tanggal Pendaftaran");
        pnlPendaftaran.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 170, -1));

        txtTglPendaftaran.setBackground(new java.awt.Color(255, 255, 255));
        txtTglPendaftaran.setForeground(new java.awt.Color(0, 0, 0));
        pnlPendaftaran.add(txtTglPendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 220, -1));

        Content.add(pnlPendaftaran, "card4");

        pnlML.setBackground(new java.awt.Color(204, 204, 204));
        pnlML.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Nama");
        pnlML.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, -1));

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("No Pendaftaran");
        pnlML.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 140, -1));

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("ID User ");
        pnlML.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtNoPendaftaranML.setBackground(new java.awt.Color(255, 255, 255));
        txtNoPendaftaranML.setForeground(new java.awt.Color(0, 0, 0));
        pnlML.add(txtNoPendaftaranML, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtIdUserML.setBackground(new java.awt.Color(255, 255, 255));
        txtIdUserML.setForeground(new java.awt.Color(0, 0, 0));
        txtIdUserML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUserMLActionPerformed(evt);
            }
        });
        pnlML.add(txtIdUserML, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtNamaML.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaML.setForeground(new java.awt.Color(0, 0, 0));
        pnlML.add(txtNamaML, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        btnHpsML.setText("HAPUS");
        btnHpsML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsMLActionPerformed(evt);
            }
        });
        pnlML.add(btnHpsML, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 80, -1));

        btnSmpnML.setText("SIMPAN");
        btnSmpnML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnMLActionPerformed(evt);
            }
        });
        pnlML.add(btnSmpnML, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        btnUbhML.setText("UBAH");
        btnUbhML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhMLActionPerformed(evt);
            }
        });
        pnlML.add(btnUbhML, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 80, -1));

        txtCariMempelaiLaki.setBackground(new java.awt.Color(255, 255, 255));
        txtCariMempelaiLaki.setForeground(new java.awt.Color(0, 0, 0));
        txtCariMempelaiLaki.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariMempelaiLakiKeyReleased(evt);
            }
        });
        pnlML.add(txtCariMempelaiLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 370, -1));

        tabelMempelaiLaki.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tabelMempelaiLaki);

        pnlML.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 760, 155));

        jLabel28.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("ID Mempelai Laki");
        pnlML.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdMempelaiLaki.setBackground(new java.awt.Color(255, 255, 255));
        txtIdMempelaiLaki.setForeground(new java.awt.Color(0, 0, 0));
        txtIdMempelaiLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMempelaiLakiActionPerformed(evt);
            }
        });
        pnlML.add(txtIdMempelaiLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        txtTempatLahirML.setBackground(new java.awt.Color(255, 255, 255));
        txtTempatLahirML.setForeground(new java.awt.Color(0, 0, 0));
        pnlML.add(txtTempatLahirML, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 220, -1));

        jLabel29.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Tempat Lahir");
        pnlML.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 110, -1));

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Pekerjaan");
        pnlML.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 90, -1));

        jLabel41.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("Agama");
        pnlML.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 140, -1));

        jLabel42.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Kawin");
        pnlML.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        txtAgamaML.setBackground(new java.awt.Color(255, 255, 255));
        txtAgamaML.setForeground(new java.awt.Color(0, 0, 0));
        pnlML.add(txtAgamaML, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 220, -1));

        txtKwnML.setBackground(new java.awt.Color(255, 255, 255));
        txtKwnML.setForeground(new java.awt.Color(0, 0, 0));
        txtKwnML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKwnMLActionPerformed(evt);
            }
        });
        pnlML.add(txtKwnML, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 220, -1));

        txtPekerjaanML.setBackground(new java.awt.Color(255, 255, 255));
        txtPekerjaanML.setForeground(new java.awt.Color(0, 0, 0));
        pnlML.add(txtPekerjaanML, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 220, -1));

        jLabel43.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Usia");
        pnlML.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        txtUsiaML.setBackground(new java.awt.Color(255, 255, 255));
        txtUsiaML.setForeground(new java.awt.Color(0, 0, 0));
        txtUsiaML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsiaMLActionPerformed(evt);
            }
        });
        pnlML.add(txtUsiaML, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 220, -1));

        txtAlamatML.setBackground(new java.awt.Color(255, 255, 255));
        txtAlamatML.setForeground(new java.awt.Color(0, 0, 0));
        pnlML.add(txtAlamatML, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 220, -1));

        jLabel44.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Alamat");
        pnlML.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 110, -1));

        jLabel45.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Pendidikan");
        pnlML.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 90, -1));

        txtPendidikanML.setBackground(new java.awt.Color(255, 255, 255));
        txtPendidikanML.setForeground(new java.awt.Color(0, 0, 0));
        pnlML.add(txtPendidikanML, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 220, -1));

        txtStatusML.setBackground(new java.awt.Color(255, 255, 255));
        txtStatusML.setForeground(new java.awt.Color(0, 0, 0));
        pnlML.add(txtStatusML, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 220, -1));

        jLabel46.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("Status");
        pnlML.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 110, -1));

        txtTanggalLahirML.setBackground(new java.awt.Color(255, 255, 255));
        txtTanggalLahirML.setForeground(new java.awt.Color(0, 0, 0));
        pnlML.add(txtTanggalLahirML, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 220, -1));

        jLabel47.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Tanggal Lahir");
        pnlML.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, -1));

        Content.add(pnlML, "card3");

        pnlMP.setBackground(new java.awt.Color(204, 204, 204));
        pnlMP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Nama");
        pnlMP.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, -1));

        jLabel49.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("No Pendaftaran");
        pnlMP.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 140, -1));

        jLabel50.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("ID User ");
        pnlMP.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtNoPendaftaranMP.setBackground(new java.awt.Color(255, 255, 255));
        txtNoPendaftaranMP.setForeground(new java.awt.Color(0, 0, 0));
        pnlMP.add(txtNoPendaftaranMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtIdUserMP.setBackground(new java.awt.Color(255, 255, 255));
        txtIdUserMP.setForeground(new java.awt.Color(0, 0, 0));
        txtIdUserMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUserMPActionPerformed(evt);
            }
        });
        pnlMP.add(txtIdUserMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtNamaMP.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaMP.setForeground(new java.awt.Color(0, 0, 0));
        pnlMP.add(txtNamaMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        btnHpsMP.setText("HAPUS");
        btnHpsMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsMPActionPerformed(evt);
            }
        });
        pnlMP.add(btnHpsMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 80, -1));

        btnSmpnMP.setText("SIMPAN");
        btnSmpnMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnMPActionPerformed(evt);
            }
        });
        pnlMP.add(btnSmpnMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        btnUbhMP.setText("UBAH");
        btnUbhMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhMPActionPerformed(evt);
            }
        });
        pnlMP.add(btnUbhMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 80, -1));

        txtCariMempelaiPerempuan.setBackground(new java.awt.Color(255, 255, 255));
        txtCariMempelaiPerempuan.setForeground(new java.awt.Color(0, 0, 0));
        txtCariMempelaiPerempuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariMempelaiPerempuanKeyReleased(evt);
            }
        });
        pnlMP.add(txtCariMempelaiPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 370, -1));

        tabelMempelaiPerempuan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tabelMempelaiPerempuan);

        pnlMP.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 760, 155));

        jLabel51.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 0));
        jLabel51.setText("ID Mempelai PR");
        pnlMP.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdMempelaiPerempuan.setBackground(new java.awt.Color(255, 255, 255));
        txtIdMempelaiPerempuan.setForeground(new java.awt.Color(0, 0, 0));
        txtIdMempelaiPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMempelaiPerempuanActionPerformed(evt);
            }
        });
        pnlMP.add(txtIdMempelaiPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        txtTempatLahirMP.setBackground(new java.awt.Color(255, 255, 255));
        txtTempatLahirMP.setForeground(new java.awt.Color(0, 0, 0));
        pnlMP.add(txtTempatLahirMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 220, -1));

        jLabel52.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 0, 0));
        jLabel52.setText("Tempat Lahir");
        pnlMP.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 110, -1));

        jLabel53.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 0, 0));
        jLabel53.setText("Pekerjaan");
        pnlMP.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 90, -1));

        jLabel54.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 0, 0));
        jLabel54.setText("Agama");
        pnlMP.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 140, -1));

        jLabel55.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 0, 0));
        jLabel55.setText("Kawin");
        pnlMP.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        txtAgamaMP.setBackground(new java.awt.Color(255, 255, 255));
        txtAgamaMP.setForeground(new java.awt.Color(0, 0, 0));
        pnlMP.add(txtAgamaMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 220, -1));

        txtKwnMP.setBackground(new java.awt.Color(255, 255, 255));
        txtKwnMP.setForeground(new java.awt.Color(0, 0, 0));
        txtKwnMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKwnMPActionPerformed(evt);
            }
        });
        pnlMP.add(txtKwnMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 220, -1));

        txtPekerjaanMP.setBackground(new java.awt.Color(255, 255, 255));
        txtPekerjaanMP.setForeground(new java.awt.Color(0, 0, 0));
        pnlMP.add(txtPekerjaanMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 220, -1));

        jLabel56.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 0, 0));
        jLabel56.setText("Usia");
        pnlMP.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        txtUsiaMP.setBackground(new java.awt.Color(255, 255, 255));
        txtUsiaMP.setForeground(new java.awt.Color(0, 0, 0));
        txtUsiaMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsiaMPActionPerformed(evt);
            }
        });
        pnlMP.add(txtUsiaMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 220, -1));

        txtAlamatMP.setBackground(new java.awt.Color(255, 255, 255));
        txtAlamatMP.setForeground(new java.awt.Color(0, 0, 0));
        pnlMP.add(txtAlamatMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 220, -1));

        jLabel57.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 0, 0));
        jLabel57.setText("Alamat");
        pnlMP.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 110, -1));

        jLabel58.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 0, 0));
        jLabel58.setText("Pendidikan");
        pnlMP.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 90, -1));

        txtPendidikanMP.setBackground(new java.awt.Color(255, 255, 255));
        txtPendidikanMP.setForeground(new java.awt.Color(0, 0, 0));
        pnlMP.add(txtPendidikanMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 220, -1));

        txtStatusMP.setBackground(new java.awt.Color(255, 255, 255));
        txtStatusMP.setForeground(new java.awt.Color(0, 0, 0));
        pnlMP.add(txtStatusMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 220, -1));

        jLabel59.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 0, 0));
        jLabel59.setText("Status");
        pnlMP.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 110, -1));

        txtTanggalLahirMP.setBackground(new java.awt.Color(255, 255, 255));
        txtTanggalLahirMP.setForeground(new java.awt.Color(0, 0, 0));
        pnlMP.add(txtTanggalLahirMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 220, -1));

        jLabel60.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 0, 0));
        jLabel60.setText("Tanggal Lahir");
        pnlMP.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, -1));

        Content.add(pnlMP, "card5");

        pnlValidasi.setBackground(new java.awt.Color(204, 204, 204));
        pnlValidasi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Tanggal ");
        pnlValidasi.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, -1));

        jLabel35.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("No Pendaftaran");
        pnlValidasi.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 140, -1));

        jLabel36.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("ID Admin ");
        pnlValidasi.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtNoPendaftaranVal.setBackground(new java.awt.Color(255, 255, 255));
        txtNoPendaftaranVal.setForeground(new java.awt.Color(0, 0, 0));
        pnlValidasi.add(txtNoPendaftaranVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 220, -1));

        txtIdAdminVal.setBackground(new java.awt.Color(255, 255, 255));
        txtIdAdminVal.setForeground(new java.awt.Color(0, 0, 0));
        txtIdAdminVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdAdminValActionPerformed(evt);
            }
        });
        pnlValidasi.add(txtIdAdminVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 220, -1));

        txtTglValidasi.setBackground(new java.awt.Color(255, 255, 255));
        txtTglValidasi.setForeground(new java.awt.Color(0, 0, 0));
        pnlValidasi.add(txtTglValidasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 220, -1));

        btnHpsVal.setText("HAPUS");
        btnHpsVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsValActionPerformed(evt);
            }
        });
        pnlValidasi.add(btnHpsVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, -1));

        btnSmpnVal.setText("SIMPAN");
        btnSmpnVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnValActionPerformed(evt);
            }
        });
        pnlValidasi.add(btnSmpnVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        btnUbhVal.setText("UBAH");
        btnUbhVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhValActionPerformed(evt);
            }
        });
        pnlValidasi.add(btnUbhVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 80, -1));

        txtCariValidasi.setBackground(new java.awt.Color(255, 255, 255));
        txtCariValidasi.setForeground(new java.awt.Color(0, 0, 0));
        txtCariValidasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariValidasiKeyReleased(evt);
            }
        });
        pnlValidasi.add(txtCariValidasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 390, -1));

        tabelValidasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tabelValidasi);

        pnlValidasi.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 480, 155));

        jLabel37.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("No Validasi");
        pnlValidasi.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtNoValidasi.setBackground(new java.awt.Color(255, 255, 255));
        txtNoValidasi.setForeground(new java.awt.Color(0, 0, 0));
        txtNoValidasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoValidasiActionPerformed(evt);
            }
        });
        pnlValidasi.add(txtNoValidasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 220, -1));

        jLabel39.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Hasil");
        pnlValidasi.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 110, -1));

        txtHasil.setBackground(new java.awt.Color(255, 255, 255));
        txtHasil.setForeground(new java.awt.Color(0, 0, 0));
        pnlValidasi.add(txtHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 220, -1));

        txtCatatanTambahan.setBackground(new java.awt.Color(255, 255, 255));
        txtCatatanTambahan.setForeground(new java.awt.Color(0, 0, 0));
        txtCatatanTambahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCatatanTambahanActionPerformed(evt);
            }
        });
        pnlValidasi.add(txtCatatanTambahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 220, -1));

        jLabel40.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Catatan Tambahan");
        pnlValidasi.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        Content.add(pnlValidasi, "card5");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("APLIKASI MANAJEMEN KUA");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(153, 153, 153));
        Menu.setForeground(new java.awt.Color(255, 255, 255));

        btnPendaftaran.setBackground(new java.awt.Color(204, 204, 204));
        btnPendaftaran.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnPendaftaran.setForeground(new java.awt.Color(0, 0, 0));
        btnPendaftaran.setText("PENDAFTARAN");
        btnPendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendaftaranActionPerformed(evt);
            }
        });

        btnML.setBackground(new java.awt.Color(204, 204, 204));
        btnML.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnML.setForeground(new java.awt.Color(0, 0, 0));
        btnML.setText("MEMPELAI LAKI LAKI");
        btnML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMLActionPerformed(evt);
            }
        });

        btnMP.setBackground(new java.awt.Color(204, 204, 204));
        btnMP.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnMP.setForeground(new java.awt.Color(0, 0, 0));
        btnMP.setText("MEMPELAI PEREMPUAN");
        btnMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMPActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(204, 204, 204));
        btnHome.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnValidasi.setBackground(new java.awt.Color(204, 204, 204));
        btnValidasi.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnValidasi.setForeground(new java.awt.Color(0, 0, 0));
        btnValidasi.setText("VALIDASI");
        btnValidasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPendaftaran, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnValidasi, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnML, btnMP, btnPendaftaran, btnValidasi});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnML)
                .addGap(18, 18, 18)
                .addComponent(btnMP)
                .addGap(18, 18, 18)
                .addComponent(btnValidasi)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnML, btnMP, btnPendaftaran, btnValidasi});

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendaftaranActionPerformed
        Content.removeAll(); 
        Content.add(pnlPendaftaran);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnPendaftaranActionPerformed

    private void btnMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMLActionPerformed
        Content.removeAll(); 
        Content.add(pnlML);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnMLActionPerformed

    private void btnMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMPActionPerformed
        Content.removeAll(); 
        Content.add(pnlMP);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnMPActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Content.removeAll(); 
        Content.add(pnlHome);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnValidasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidasiActionPerformed
        Content.removeAll(); 
        Content.add(pnlValidasi);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnValidasiActionPerformed

    private void txtCariPendaftaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariPendaftaranKeyReleased
        String c = txtCariPendaftaran.getText();
        String cari = "SELECT*FROM pendaftaran WHERE no_pendaftaran LIKE '%"+c+"%'"+
                      "OR id_admin LIKE '%"+c+"%' OR kode_kelurahan LIKE '%"+c+"%'"+
                      "OR tgl_pendaftaran LIKE '%"+c+"%' OR status LIKE '%"+c+"%'";
        mycode.tampilDataPendaftaran(tabelPendaftaran, cari);
    }//GEN-LAST:event_txtCariPendaftaranKeyReleased

    private void btnUbhPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhPenActionPerformed
        try {
            mycode.ubahPendaftaran(txtNoPendaftaran.getText(), txtIdAdminPen.getText(),
                                   txtKodeKelurahan.getText(), txtTglPendaftaran.getText(),
                                   txtTglPernikahan.getText(), txtStatusPen.getText());

            // Refresh tabel
            mycode.tampilDataPendaftaran(tabelPendaftaran, "SELECT*FROM pendaftaran");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhPenActionPerformed

    private void btnSmpnPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnPenActionPerformed
        try {
        if(txtNoPendaftaran.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No Pendaftaran Belum Diisi");
                txtNoPendaftaran.requestFocus();
            } else if(txtIdAdminPen.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "ID Admin Belum Diisi");
                txtIdAdminPen.requestFocus();
            } else if(txtKodeKelurahan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Kode Kelurahan Belum Diisi");
                txtKodeKelurahan.requestFocus();
            } else if(txtTglPendaftaran.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tgl Pendaftaran Belum Diisi");
                txtTglPendaftaran.requestFocus();
            } else if(txtTglPernikahan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tgl Pernikahan Belum Diisi");
                txtTglPernikahan.requestFocus();
            } else if(txtStatusPen.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Status Belum Diisi");
                txtStatusPen.requestFocus();
            } else {
                mycode.simpanPendaftaran02(txtNoPendaftaran.getText(), txtIdAdminPen.getText(),
                                           txtKodeKelurahan.getText(), txtTglPendaftaran.getText(),
                                           txtTglPernikahan.getText(), txtStatusPen.getText());

                // Refresh tabel
                mycode.tampilDataPendaftaran(tabelPendaftaran, "SELECT*FROM pendaftaran");

                // Cek duplikasi
                if (mycode.duplikasi == true){
                    txtIdAdminPen.setText(mycode.CEK_ID_ADMIN_PEN);
                    txtKodeKelurahan.setText(mycode.CEK_KODE_KELURAHAN_PEN);
                    txtTglPendaftaran.setText(mycode.CEK_TGL_PENDAFTARAN);
                    txtTglPernikahan.setText(mycode.CEK_TGL_PERNIKAHAN);
                    txtStatusPen.setText(mycode.CEK_STATUS_PEN);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnPenActionPerformed

    private void btnHpsPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsPenActionPerformed
        try {
            mycode.hapusPendaftaran(txtNoPendaftaran.getText());
            mycode.tampilDataPendaftaran(tabelPendaftaran, "SELECT*FROM pendaftaran");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsPenActionPerformed

    private void txtIdAdminPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAdminPenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAdminPenActionPerformed

    private void txtNoPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoPendaftaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoPendaftaranActionPerformed

    private void txtIdUserMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUserMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUserMLActionPerformed

    private void btnHpsMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsMLActionPerformed
        try {
            mycode.hapusMempelaiLaki(txtIdMempelaiLaki.getText());
            mycode.tampilDataMempelaiLaki(tabelMempelaiLaki, "SELECT*FROM mempelai_laki_laki");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsMLActionPerformed

    private void btnSmpnMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnMLActionPerformed
        try {
            if(txtIdMempelaiLaki.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Mempelai Laki-laki Belum Diisi");
                txtIdMempelaiLaki.requestFocus();
            } else if(txtIdUserML.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "ID User Belum Diisi");
                txtIdUserML.requestFocus();
            } else if(txtNoPendaftaranML.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "No Pendaftaran Belum Diisi");
                txtNoPendaftaranML.requestFocus();
            } else if(txtNamaML.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Belum Diisi");
                txtNamaML.requestFocus();
            } else if(txtTempatLahirML.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tempat Lahir Belum Diisi");
                txtTempatLahirML.requestFocus();
            } else if(txtTanggalLahirML.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tgl Lahir Belum Diisi");
                txtTanggalLahirML.requestFocus();
            } else if(txtUsiaML.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Usia Belum Diisi");
                txtUsiaML.requestFocus();
            } else if(txtKwnML.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Kewarganegaraan Belum Diisi");
                txtKwnML.requestFocus();
            } else if(txtAgamaML.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Agama Belum Diisi");
                txtAgamaML.requestFocus();
            } else if(txtPekerjaanML.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Pekerjaan Belum Diisi");
                txtPekerjaanML.requestFocus();
            } else if(txtAlamatML.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Alamat Belum Diisi");
                txtAlamatML.requestFocus();
            } else if(txtPendidikanML.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Pendidikan Belum Diisi");
                txtPendidikanML.requestFocus();
            } else if(txtStatusML.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Status Belum Diisi");
                txtStatusML.requestFocus();
            // Validasi txtFotoML DIHILANGKAN
            } else {
                mycode.simpanMempelaiLaki02(txtIdMempelaiLaki.getText(), txtIdUserML.getText(),
                                            txtNoPendaftaranML.getText(), txtNamaML.getText(),
                                            txtTempatLahirML.getText(), txtTanggalLahirML.getText(),
                                            txtUsiaML.getText(), txtKwnML.getText(),
                                            txtAgamaML.getText(), txtPekerjaanML.getText(),
                                            txtAlamatML.getText(), txtPendidikanML.getText(),
                                            txtStatusML.getText());

                mycode.tampilDataMempelaiLaki(tabelMempelaiLaki, "SELECT*FROM mempelai_laki_laki");

                if (mycode.duplikasi == true){
                    txtIdUserML.setText(mycode.CEK_ID_USER_ML);
                    txtNoPendaftaranML.setText(mycode.CEK_NO_PENDAFTARAN_ML);
                    txtNamaML.setText(mycode.CEK_NAMA_ML);
                    txtTempatLahirML.setText(mycode.CEK_TEMPAT_LAHIR_ML);
                    txtTanggalLahirML.setText(mycode.CEK_TGL_LAHIR_ML);
                    txtUsiaML.setText(mycode.CEK_USIA_ML);
                    txtKwnML.setText(mycode.CEK_KWN_ML);
                    txtAgamaML.setText(mycode.CEK_AGAMA_ML);
                    txtPekerjaanML.setText(mycode.CEK_PEKERJAAN_ML);
                    txtAlamatML.setText(mycode.CEK_ALAMAT_ML);
                    txtPendidikanML.setText(mycode.CEK_PENDIDIKAN_ML);
                    txtStatusML.setText(mycode.CEK_STATUS_ML);
                    // Pengisian txtFotoML DIHILANGKAN
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnMLActionPerformed

    private void btnUbhMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhMLActionPerformed
        try {
            mycode.ubahMempelaiLaki(txtIdMempelaiLaki.getText(), txtIdUserML.getText(),
                                    txtNoPendaftaranML.getText(), txtNamaML.getText(),
                                    txtTempatLahirML.getText(), txtTanggalLahirML.getText(),
                                    txtUsiaML.getText(), txtKwnML.getText(),
                                    txtAgamaML.getText(), txtPekerjaanML.getText(),
                                    txtAlamatML.getText(), txtPendidikanML.getText(),
                                    txtStatusML.getText());

            mycode.tampilDataMempelaiLaki(tabelMempelaiLaki, "SELECT*FROM mempelai_laki_laki");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhMLActionPerformed

    private void txtCariMempelaiLakiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariMempelaiLakiKeyReleased
        String c = txtCariMempelaiLaki.getText();
        String cari = "SELECT*FROM mempelai_laki_laki WHERE id_mempelai_laki LIKE '%"+c+"%'"+
                      "OR no_pendaftaran LIKE '%"+c+"%' OR nama LIKE '%"+c+"%'"+
                      "OR tempat_lahir LIKE '%"+c+"%' OR alamat LIKE '%"+c+"%'";
        mycode.tampilDataMempelaiLaki(tabelMempelaiLaki, cari);
    }//GEN-LAST:event_txtCariMempelaiLakiKeyReleased

    private void txtIdMempelaiLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMempelaiLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMempelaiLakiActionPerformed

    private void txtIdAdminValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAdminValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAdminValActionPerformed

    private void btnHpsValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsValActionPerformed
        try {
            mycode.hapusValidasi(txtNoValidasi.getText());
            mycode.tampilDataValidasi(tabelValidasi, "SELECT*FROM validasi");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsValActionPerformed

    private void btnSmpnValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnValActionPerformed
        try {
            if(txtNoValidasi.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No Validasi Belum Diisi");
                txtNoValidasi.requestFocus();
            } else if(txtIdAdminVal.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "ID Admin Belum Diisi");
                txtIdAdminVal.requestFocus();
            } else if(txtNoPendaftaranVal.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "No Pendaftaran Belum Diisi");
                txtNoPendaftaranVal.requestFocus();
            } else if(txtTglValidasi.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tgl Validasi Belum Diisi");
                txtTglValidasi.requestFocus();
            } else if(txtCatatanTambahan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Catatan Tambahan Belum Diisi");
                txtCatatanTambahan.requestFocus();
            } else if(txtHasil.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Hasil Belum Diisi");
                txtHasil.requestFocus();
            } else {
                mycode.simpanValidasi02(txtNoValidasi.getText(), txtIdAdminVal.getText(),
                                        txtNoPendaftaranVal.getText(), txtTglValidasi.getText(),
                                        txtCatatanTambahan.getText(), txtHasil.getText());

                // Refresh tabel
                mycode.tampilDataValidasi(tabelValidasi, "SELECT*FROM validasi");

                // Cek duplikasi
                if (mycode.duplikasi == true){
                    txtIdAdminVal.setText(mycode.CEK_ID_ADMIN_VAL);
                    txtNoPendaftaranVal.setText(mycode.CEK_NO_PENDAFTARAN_VAL);
                    txtTglValidasi.setText(mycode.CEK_TGL_VALIDASI);
                    txtCatatanTambahan.setText(mycode.CEK_CATATAN_TAMBAHAN);
                    txtHasil.setText(mycode.CEK_HASIL);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnValActionPerformed

    private void btnUbhValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhValActionPerformed
        try {
            mycode.ubahValidasi(txtNoValidasi.getText(), txtIdAdminVal.getText(),
                                txtNoPendaftaranVal.getText(), txtTglValidasi.getText(),
                                txtCatatanTambahan.getText(), txtHasil.getText());

            // Refresh tabel
            mycode.tampilDataValidasi(tabelValidasi, "SELECT*FROM validasi");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhValActionPerformed

    private void txtCariValidasiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariValidasiKeyReleased
        String c = txtCariValidasi.getText();
        String cari = "SELECT*FROM validasi WHERE no_validasi LIKE '%"+c+"%'"+
                      "OR id_admin LIKE '%"+c+"%' OR no_pendaftaran LIKE '%"+c+"%'"+
                      "OR tgl_validasi LIKE '%"+c+"%' OR hasil LIKE '%"+c+"%'";
        mycode.tampilDataValidasi(tabelValidasi, cari);
    }//GEN-LAST:event_txtCariValidasiKeyReleased

    private void txtNoValidasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoValidasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoValidasiActionPerformed

    private void txtCatatanTambahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCatatanTambahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCatatanTambahanActionPerformed

    private void txtKwnMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKwnMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKwnMLActionPerformed

    private void txtUsiaMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsiaMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsiaMLActionPerformed

    private void txtIdUserMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUserMPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUserMPActionPerformed

    private void btnHpsMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsMPActionPerformed
        try {
            mycode.hapusMempelaiPerempuan(txtIdMempelaiPerempuan.getText());
            mycode.tampilDataMempelaiPerempuan(tabelMempelaiPerempuan, "SELECT*FROM mempelai_perempuan");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsMPActionPerformed

    private void btnSmpnMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnMPActionPerformed
        try {
            if(txtIdMempelaiPerempuan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Mempelai Perempuan Belum Diisi");
                txtIdMempelaiPerempuan.requestFocus();
            } else if(txtIdUserMP.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "ID User Belum Diisi");
                txtIdUserMP.requestFocus();
            } else if(txtNoPendaftaranMP.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "No Pendaftaran Belum Diisi");
                txtNoPendaftaranMP.requestFocus();
            } else if(txtNamaMP.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Belum Diisi");
                txtNamaMP.requestFocus();
            } else if(txtTempatLahirMP.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tempat Lahir Belum Diisi");
                txtTempatLahirMP.requestFocus();
            } else if(txtTanggalLahirMP.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tgl Lahir Belum Diisi");
                txtTanggalLahirMP.requestFocus();
            } else if(txtUsiaMP.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Usia Belum Diisi");
                txtUsiaMP.requestFocus();
            } else if(txtKwnMP.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Kewarganegaraan Belum Diisi");
                txtKwnMP.requestFocus();
            } else if(txtAgamaMP.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Agama Belum Diisi");
                txtAgamaMP.requestFocus();
            } else if(txtPekerjaanMP.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Pekerjaan Belum Diisi");
                txtPekerjaanMP.requestFocus();
            } else if(txtAlamatMP.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Alamat Belum Diisi");
                txtAlamatMP.requestFocus();
            } else if(txtPendidikanMP.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Pendidikan Belum Diisi");
                txtPendidikanMP.requestFocus();
            } else if(txtStatusMP.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Status Belum Diisi");
                txtStatusMP.requestFocus();
            // Validasi txtFotoMP DIHILANGKAN
            } else {
                mycode.simpanMempelaiPerempuan02(txtIdMempelaiPerempuan.getText(), txtIdUserMP.getText(),
                                                txtNoPendaftaranMP.getText(), txtNamaMP.getText(),
                                                txtTempatLahirMP.getText(), txtTanggalLahirMP.getText(),
                                                txtUsiaMP.getText(), txtKwnMP.getText(),
                                                txtAgamaMP.getText(), txtPekerjaanMP.getText(),
                                                txtAlamatMP.getText(), txtPendidikanMP.getText(),
                                                txtStatusMP.getText());

                // Refresh tabel
                mycode.tampilDataMempelaiPerempuan(tabelMempelaiPerempuan, "SELECT*FROM mempelai_perempuan");

                // Cek duplikasi
                if (mycode.duplikasi == true){
                    txtIdUserMP.setText(mycode.CEK_ID_USER_MP);
                    txtNoPendaftaranMP.setText(mycode.CEK_NO_PENDAFTARAN_MP);
                    txtNamaMP.setText(mycode.CEK_NAMA_MP);
                    txtTempatLahirMP.setText(mycode.CEK_TEMPAT_LAHIR_MP);
                    txtTanggalLahirMP.setText(mycode.CEK_TGL_LAHIR_MP);
                    txtUsiaMP.setText(mycode.CEK_USIA_MP);
                    txtKwnMP.setText(mycode.CEK_KWN_MP);
                    txtAgamaMP.setText(mycode.CEK_AGAMA_MP);
                    txtPekerjaanMP.setText(mycode.CEK_PEKERJAAN_MP);
                    txtAlamatMP.setText(mycode.CEK_ALAMAT_MP);
                    txtPendidikanMP.setText(mycode.CEK_PENDIDIKAN_MP);
                    txtStatusMP.setText(mycode.CEK_STATUS_MP);
                    // Pengisian txtFotoMP DIHILANGKAN
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnMPActionPerformed

    private void btnUbhMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhMPActionPerformed
        try {
            mycode.ubahMempelaiPerempuan(txtIdMempelaiPerempuan.getText(), txtIdUserMP.getText(),
                                        txtNoPendaftaranMP.getText(), txtNamaMP.getText(),
                                        txtTempatLahirMP.getText(), txtTanggalLahirMP.getText(),
                                        txtUsiaMP.getText(), txtKwnMP.getText(),
                                        txtAgamaMP.getText(), txtPekerjaanMP.getText(),
                                        txtAlamatMP.getText(), txtPendidikanMP.getText(),
                                        txtStatusMP.getText());

            // Refresh tabel
            mycode.tampilDataMempelaiPerempuan(tabelMempelaiPerempuan, "SELECT*FROM mempelai_perempuan");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhMPActionPerformed

    private void txtCariMempelaiPerempuanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariMempelaiPerempuanKeyReleased
        String c = txtCariMempelaiPerempuan.getText();
        String cari = "SELECT*FROM mempelai_perempuan WHERE id_mempelai_perempuan LIKE '%"+c+"%'"+
                      "OR no_pendaftaran LIKE '%"+c+"%' OR nama LIKE '%"+c+"%'"+
                      "OR tempat_lahir LIKE '%"+c+"%' OR alamat LIKE '%"+c+"%'";
        mycode.tampilDataMempelaiPerempuan(tabelMempelaiPerempuan, cari);
    }//GEN-LAST:event_txtCariMempelaiPerempuanKeyReleased

    private void txtIdMempelaiPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMempelaiPerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMempelaiPerempuanActionPerformed

    private void txtKwnMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKwnMPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKwnMPActionPerformed

    private void txtUsiaMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsiaMPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsiaMPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHpsML;
    private javax.swing.JButton btnHpsMP;
    private javax.swing.JButton btnHpsPen;
    private javax.swing.JButton btnHpsVal;
    private javax.swing.JButton btnML;
    private javax.swing.JButton btnMP;
    private javax.swing.JButton btnPendaftaran;
    private javax.swing.JButton btnSmpnML;
    private javax.swing.JButton btnSmpnMP;
    private javax.swing.JButton btnSmpnPen;
    private javax.swing.JButton btnSmpnVal;
    private javax.swing.JButton btnUbhML;
    private javax.swing.JButton btnUbhMP;
    private javax.swing.JButton btnUbhPen;
    private javax.swing.JButton btnUbhVal;
    private javax.swing.JButton btnValidasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlML;
    private javax.swing.JPanel pnlMP;
    private javax.swing.JPanel pnlPendaftaran;
    private javax.swing.JPanel pnlValidasi;
    private javax.swing.JTable tabelMempelaiLaki;
    private javax.swing.JTable tabelMempelaiPerempuan;
    private javax.swing.JTable tabelPendaftaran;
    private javax.swing.JTable tabelValidasi;
    private javax.swing.JTextField txtAgamaML;
    private javax.swing.JTextField txtAgamaMP;
    private javax.swing.JTextField txtAlamatML;
    private javax.swing.JTextField txtAlamatMP;
    private javax.swing.JTextField txtCariMempelaiLaki;
    private javax.swing.JTextField txtCariMempelaiPerempuan;
    private javax.swing.JTextField txtCariPendaftaran;
    private javax.swing.JTextField txtCariValidasi;
    private javax.swing.JTextField txtCatatanTambahan;
    private javax.swing.JTextField txtHasil;
    private javax.swing.JTextField txtIdAdminPen;
    private javax.swing.JTextField txtIdAdminVal;
    private javax.swing.JTextField txtIdMempelaiLaki;
    private javax.swing.JTextField txtIdMempelaiPerempuan;
    private javax.swing.JTextField txtIdUserML;
    private javax.swing.JTextField txtIdUserMP;
    private javax.swing.JTextField txtKodeKelurahan;
    private javax.swing.JTextField txtKwnML;
    private javax.swing.JTextField txtKwnMP;
    private javax.swing.JTextField txtNamaML;
    private javax.swing.JTextField txtNamaMP;
    private javax.swing.JTextField txtNoPendaftaran;
    private javax.swing.JTextField txtNoPendaftaranML;
    private javax.swing.JTextField txtNoPendaftaranMP;
    private javax.swing.JTextField txtNoPendaftaranVal;
    private javax.swing.JTextField txtNoValidasi;
    private javax.swing.JTextField txtPekerjaanML;
    private javax.swing.JTextField txtPekerjaanMP;
    private javax.swing.JTextField txtPendidikanML;
    private javax.swing.JTextField txtPendidikanMP;
    private javax.swing.JTextField txtStatusML;
    private javax.swing.JTextField txtStatusMP;
    private javax.swing.JTextField txtStatusPen;
    private javax.swing.JTextField txtTanggalLahirML;
    private javax.swing.JTextField txtTanggalLahirMP;
    private javax.swing.JTextField txtTempatLahirML;
    private javax.swing.JTextField txtTempatLahirMP;
    private javax.swing.JTextField txtTglPendaftaran;
    private javax.swing.JTextField txtTglPernikahan;
    private javax.swing.JTextField txtTglValidasi;
    private javax.swing.JTextField txtUsiaML;
    private javax.swing.JTextField txtUsiaMP;
    // End of variables declaration//GEN-END:variables
}
